"""Self-contained HTML report.

One file, no external assets: no CDN link, no webfont, no script that fetches
anything. It has to open from a filesystem in five years and may be attached
to a regulatory submission (design.md section 9).

The run timestamp appears here and only here. JSON output stays free of it so
two runs diff cleanly; in a report meant for a human it is metadata rather
than content.
"""

from __future__ import annotations

import html
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import TextIO

from ..checks import CheckOutcome, findings_from
from ..finding import Finding, Severity
from ..model import Workflow
from ..score import MAX_SCORE, compute

TEMPLATE = Path(__file__).resolve().parent / "template.html"


def _esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def _severity_section(workflow: Workflow, severity: Severity, findings: list[Finding]) -> str:
    rows = []
    for finding in findings:
        evidence = (
            f'<span class="evidence">{_esc(finding.evidence)}</span>' if finding.evidence else ""
        )
        rows.append(
            "<tr>"
            f'<td class="id">{_esc(finding.id)}</td>'
            f'<td class="loc">{_esc(workflow.rel(finding.file))}:{finding.line}</td>'
            f"<td>{_esc(finding.problem)}{evidence}"
            f'<span class="fix"><b>Fix:</b> {_esc(finding.fix)}</span></td>'
            "</tr>"
        )
    return (
        f'<h2 class="{severity.label}">{severity.label.upper()} ({len(findings)})</h2>'
        '<div class="wrap"><table>'
        "<thead><tr><th>Check</th><th>Location</th><th>Problem and fix</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def build(workflow: Workflow, outcomes: list[CheckOutcome]) -> str:
    """Render the complete HTML document as a string."""
    findings = findings_from(outcomes)
    score = compute(findings, outcomes)
    source = workflow.source

    grouped: dict[Severity, list[Finding]] = defaultdict(list)
    for finding in findings:
        grouped[finding.severity].append(finding)

    identity = [f"{sum(1 for p in workflow.processes if not p.synthetic)} processes"]
    if source.declared_version:
        identity.append(f"version {source.declared_version}")
    if source.is_repo and source.commit != "UNRESOLVED":
        identity.append(f"commit {source.commit[:8]}")
    if source.tag:
        identity.append(f"tag {source.tag}")

    counts_html = (
        "".join(
            f"<span><b>{count}</b> {severity.label}</span>"
            for severity, count in sorted(score.counts.items(), key=lambda kv: kv[0].rank)
            if count
        )
        or "<span>no findings</span>"
    )

    parts = [
        f"<h1>Provenix report — {_esc(workflow.root.name)}</h1>",
        f'<p class="sub">{_esc(workflow.engine)} &middot; {_esc(" &middot; ".join(identity))}</p>'.replace(
            "&amp;middot;", "&middot;"
        ),
        '<div class="summary">',
        f'<div class="score">{score.value}<small>&nbsp;/ {MAX_SCORE}</small></div>',
        f'<div class="counts">{counts_html}</div>',
        f'<div class="counts"><span>{score.checks_run} checks run, '
        f"{score.checks_skipped} not applicable</span></div>",
        "</div>",
    ]

    if findings:
        for severity in sorted(grouped, key=lambda s: s.rank):
            parts.append(_severity_section(workflow, severity, grouped[severity]))
    else:
        parts.append('<div class="clean">No findings.</div>')

    skipped = [o for o in outcomes if not o.applicable]
    if skipped:
        items = "".join(
            f"<li><b>{_esc(o.spec.id)}</b> — {_esc(o.skipped_reason)}</li>" for o in skipped
        )
        parts.append(
            '<div class="note"><b>Checks not run.</b> These did not apply to this '
            "pipeline and do not affect the score."
            f'<ul class="plain">{items}</ul></div>'
        )

    if workflow.excluded_test_urls:
        count = len(workflow.excluded_test_urls)
        files = len({a.file for a in workflow.excluded_test_urls})
        parts.append(
            f'<div class="note"><b>Excluded from PVX004/005.</b> {count} reference '
            f"URL{'s' if count != 1 else ''} across {files} file{'s' if files != 1 else ''} "
            "belong to CI test profiles rather than to the analysis, and were not "
            "assessed.</div>"
        )

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts.append(
        f"<footer>Generated by Provenix on {generated}. Static analysis only — the "
        "pipeline was never executed. Score: 100 minus 15 per critical, 7 per high, "
        "3 per medium, 20 per security finding, floored at 0.</footer>"
    )

    template = TEMPLATE.read_text(encoding="utf-8")
    return template.replace("__PIPELINE__", _esc(workflow.root.name)).replace(
        "__BODY__", "\n".join(parts)
    )


def render(workflow: Workflow, outcomes: list[CheckOutcome], stream: TextIO | None = None) -> None:
    out = stream if stream is not None else sys.stdout
    out.write(build(workflow, outcomes))
